//-------------------------------------------------------------------------------
//                                                                               
//    This code was automatically generated.                                     
//    Changes to this file may cause incorrect behavior and will be lost if      
//    the code is regenerated.                                                   
//                                                                               
//-------------------------------------------------------------------------------

namespace GameDatabase.Enums
{
	public enum StatModificationType
	{
		None = 0,
		WeaponDamage = 1,
		WeaponRange = 2,
		WeaponFireRate = 3,
		WeaponBulletSpeed = 4,
		WeaponBulletMass = 5,
		WeaponAoe = 6,
		WeaponEnergyCost = 7,
		WeaponRecoil = 8,
		DroneAttack = 10,
		DroneDefense = 11,
		DroneSpeed = 12,
		DroneRange = 13,
		DroneReconstructionTime = 14,
		EnergyCapacity = 20,
		EnergyRechargeRate = 21,
		ShieldPoints = 22,
		ShieldRechargeRate = 23,
		ArmorPoints = 24,
		ArmorRepairRate = 25,
		ShieldRechargeCooldown = 26,
		Resistance = 30,
		KineticResistance = 31,
		ThermalResistance = 32,
		EnergyResistance = 33,
		EnergyAbsorption = 34,
		RammingDamage = 35,
		DeviceCooldown = 40,
		DeviceRange = 41,
		DevicePower = 42,
		EnginePower = 50,
		EngineTurnRate = 51,
		Mass = 60,
		EnergyCost = 61,
		ExtraHitPoints = 62,
		WeightReduction = 63,
		FlatShieldPoints = 70,
		FlatShieldRechargeRate = 71,
		FlatEnergyCapacity = 72,
		FlatEnergyRecharge = 73,
		FlatEnginePower = 74,
		FlatTurnRate = 75,
		FlatMass = 76,
		FlatArmorRepairRate = 77,
		FlatWeightReduction = 78,
		FlatEnergyCost = 79,
		FlatEnergyAbsorption = 80,
		FlatRammingDamage = 81,
		FlatKineticResistance = 82,
		FlatThermalResistance = 83,
		FlatEnergyResistance = 84,
		FlatDroneReconstructionSpeed = 85,
		FlatWeaponDamage = 90,
		FlatWeaponRange = 91,
		FlatWeaponFireRate = 92,
		FlatWeaponBulletSpeed = 93,
		FlatWeaponBulletMass = 94,
		FlatWeaponAoe = 95,
		FlatWeaponEnergyCost = 96,
		FlatWeaponRecoil = 97,
		FlatDeviceCooldown = 100,
		FlatDeviceRange = 101,
		FlatDevicePower = 102,
		FlatDroneRange = 105,
	}
}
